services:
  - type: web
    name: shopee-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.shopee_affiliate_auth:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: SHOPEE_APP_ID
        sync: false
      - key: SHOPEE_APP_SECRET
        sync: false
      - key: SHOPEE_AFFILIATE_API_URL
        value: https://open-api.affiliate.shopee.com.br
      - key: TOKEN_ENCRYPTION_KEY
        sync: false